// core/solid/useSSEWithSharedWorker.ts
import { createSignal, onCleanup } from 'solid-js';
import { SSESharedWorkerClient } from '../shared/sse-shared-worker-client';
import type { SSEOptions } from '../shared/types';

export function useSSEWithSharedWorker<
  TEventData = unknown,
  TEventType extends string = string,
>(
  endpointUrl: string | null,
  options: SSEOptions = {},
  workerPath = '/shared-worker.js'
) {
  const sharedWorkerClient = new SSESharedWorkerClient<TEventData, TEventType>(
    endpointUrl,
    options,
    workerPath
  );
  const snapshot = sharedWorkerClient.getSnapshot();

  const [status, setStatus] = createSignal(snapshot.status);
  const [lastEvent, setLastEvent] = createSignal(snapshot.lastEvent);
  const [events, setEvents] = createSignal(snapshot.events);
  const [error, setError] = createSignal(snapshot.error);
  const [retryCount, setRetryCount] = createSignal(snapshot.retryCount);

  const unsubscribe = sharedWorkerClient.subscribe((nextState) => {
    setStatus(nextState.status);
    setLastEvent(nextState.lastEvent);
    setEvents(nextState.events);
    setError(nextState.error);
    setRetryCount(nextState.retryCount);
  });

  onCleanup(() => {
    unsubscribe();
    sharedWorkerClient.destroy();
  });

  return {
    status,
    lastEvent,
    events,
    error,
    retryCount,
    connect: () => sharedWorkerClient.connect(),
    close: () => sharedWorkerClient.close(),
    reconnect: () => sharedWorkerClient.reconnect(),
  };
}

// core/react/useSSEWithSharedWorker.ts
import { useEffect, useMemo, useState } from 'react';
import { SSESharedWorkerClient } from '../shared/sse-shared-worker-client';
import type { SSEOptions, SSEReturn } from '../shared/types';

export function useSSEWithSharedWorker<
  TEventData = unknown,
  TEventType extends string = string,
>(
  endpointUrl: string | null,
  options: SSEOptions = {},
  workerPath = '/shared-worker.js'
): SSEReturn<TEventData, TEventType> {
  const sharedWorkerClient = useMemo(
    () =>
      new SSESharedWorkerClient<TEventData, TEventType>(
        endpointUrl,
        options,
        workerPath
      ),
    [endpointUrl, options, workerPath]
  );

  const [state, setState] = useState(() => sharedWorkerClient.getSnapshot());

  useEffect(() => {
    const unsubscribe = sharedWorkerClient.subscribe(setState);
    return () => {
      unsubscribe();
      sharedWorkerClient.destroy();
    };
  }, [sharedWorkerClient]);

  return {
    ...state,
    connect: () => sharedWorkerClient.connect(),
    close: () => sharedWorkerClient.close(),
    reconnect: () => sharedWorkerClient.reconnect(),
  };
}
