// core/solid/useSSE.ts
import { createSignal, onCleanup } from 'solid-js';
import { SSEClient } from '../shared/sse-client';
import type { SSEOptions } from '../shared/types';

export function useSSE<TEventData = unknown, TEventType extends string = string>(
  endpointUrl: string | null,
  options: SSEOptions = {}
) {
  const sseClient = new SSEClient<TEventData, TEventType>(endpointUrl, options);
  const snapshot = sseClient.getSnapshot();

  const [status, setStatus] = createSignal(snapshot.status);
  const [lastEvent, setLastEvent] = createSignal(snapshot.lastEvent);
  const [events, setEvents] = createSignal(snapshot.events);
  const [error, setError] = createSignal(snapshot.error);
  const [retryCount, setRetryCount] = createSignal(snapshot.retryCount);

  const unsubscribe = sseClient.subscribe((nextState) => {
    setStatus(nextState.status);
    setLastEvent(nextState.lastEvent);
    setEvents(nextState.events);
    setError(nextState.error);
    setRetryCount(nextState.retryCount);
  });

  onCleanup(() => {
    unsubscribe();
    sseClient.destroy();
  });

  return {
    status,
    lastEvent,
    events,
    error,
    retryCount,
    connect: () => sseClient.connect(),
    close: () => sseClient.close(),
    reconnect: () => sseClient.reconnect(),
  };
}

// core/react/useSSE.ts
import { useEffect, useMemo, useState } from 'react';
import { SSEClient } from '../shared/sse-client';
import type { SSEOptions, SSEReturn } from '../shared/types';

export function useSSE<TEventData = unknown, TEventType extends string = string>(
  endpointUrl: string | null,
  options: SSEOptions = {}
): SSEReturn<TEventData, TEventType> {
  const sseClient = useMemo(
    () => new SSEClient<TEventData, TEventType>(endpointUrl, options),
    [endpointUrl, options]
  );

  const [state, setState] = useState(() => sseClient.getSnapshot());

  useEffect(() => {
    const unsubscribe = sseClient.subscribe(setState);
    return () => {
      unsubscribe();
      sseClient.destroy();
    };
  }, [sseClient]);

  return {
    ...state,
    connect: () => sseClient.connect(),
    close: () => sseClient.close(),
    reconnect: () => sseClient.reconnect(),
  };
}
